/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddAddress: typeof import('./src/components/pages/User/views/AddAddress.vue')['default']
    Address: typeof import('./src/components/pages/User/views/Address.vue')['default']
    BaseLayout: typeof import('./src/components/layout/BaseLayout.vue')['default']
    Coupon: typeof import('./src/components/pages/User/views/Coupon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Index: typeof import('./src/components/pages/Index/Index.vue')['default']
    Login: typeof import('./src/components/pages/User/views/Login.vue')['default']
    Map: typeof import('./src/components/pages/User/views/Map.vue')['default']
    Order: typeof import('./src/components/pages/Order/Order.vue')['default']
    Phone: typeof import('./src/components/pages/User/views/Phone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/pages/Index/views/Search.vue')['default']
    Shop: typeof import('./src/components/pages/Index/views/Shop.vue')['default']
    UpdateAddress: typeof import('./src/components/pages/User/views/UpdateAddress.vue')['default']
    User: typeof import('./src/components/pages/User/User.vue')['default']
    VanAddressList: typeof import('vant/es')['AddressList']
    VanButton: typeof import('vant/es')['Button']
    VanButtton: typeof import('vant/es')['Buttton']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanContactCard: typeof import('vant/es')['ContactCard']
    VanCouponList: typeof import('vant/es')['CouponList']
    VanDivider: typeof import('vant/es')['Divider']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSpace: typeof import('vant/es')['Space']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
  }
}
